version: '3.8'

services:
  db: 
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backend/scripts/seed.sql:/docker-entrypoint-initdb.d/seed_db.sql
    restart: always
    env_file: ./backend/.env
    ports:
      - 5432:5432
  app:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000